import { Property } from "../types";

export const mockProperties: Property[] = [
    {
        id: 1,
        title: "شقة فاخرة في حي حدة",
        description: "شقة واسعة ومفروشة بالكامل في أرقى أحياء صنعاء. قريبة من الخدمات والمطاعم.",
        type: "apartment",
        price: 150000,
        city: "صنعاء",
        district: "حدة",
        area: 120,
        rooms: 3,
        bathrooms: 2,
        floor: 3,
        features: ["مفروش", "مصعد", "كراج", "حراسة"],
        images: ["/Check-/images/luxury_apartment_sanaa.png"],
        status: "available",
        created_at: new Date().toISOString()
    },
    {
        id: 2,
        title: "فيلا مودرن في مدينة الأصبحي",
        description: "فيلا مستقلة بتصميم حديث مع حديقة واسعة ومسبح. مثالية للعائلات الكبيرة.",
        type: "villa",
        price: 450000,
        city: "صنعاء",
        district: "الأصبحي",
        area: 350,
        rooms: 6,
        bathrooms: 4,
        floor: 2,
        features: ["حديقة", "مسبح", "تكييف", "نظام أمني"],
        images: ["/Check-/images/modern_villa_garden.png"],
        status: "available",
        created_at: new Date().toISOString()
    },
    {
        id: 3,
        title: "مكتب تجاري في شارع الستين",
        description: "مساحة مكتبية جاهزة في موقع استراتيجي. تتوفر مواقف سيارات وخدمات إنترنت.",
        type: "office",
        price: 200000,
        city: "صنعاء",
        district: "الستين",
        area: 80,
        rooms: 2,
        bathrooms: 1,
        floor: 5,
        features: ["إنترنت", "تكييف", "مواقف"],
        images: ["/Check-/images/commercial_office_space.png"],
        status: "available",
        created_at: new Date().toISOString()
    },
    {
        id: 4,
        title: "منزل تقليدي في صنعاء القديمة",
        description: "منزل أثري تم ترميمه بعناية ليجمع بين عبق التاريخ ووسائل الراحة الحديثة. تجربة فريدة للسكن.",
        type: "house",
        price: 180000,
        city: "صنعاء",
        district: "صنعاء القديمة",
        area: 200,
        rooms: 4,
        bathrooms: 3,
        floor: 4,
        features: ["تاريخي", "ترميم حديث", "إطلالة بانورامية"],
        images: ["/Check-/images/traditional_house_old_sanaa.png"],
        status: "available",
        created_at: new Date().toISOString()
    },
    {
        id: 5,
        title: "شقة عصرية مع مطبخ مجهز",
        description: "شقة تتميز بتصميم داخلي أنيق ومطبخ عصري مجهز بالكامل بأحدث الأجهزة.",
        type: "apartment",
        price: 120000,
        city: "صنعاء",
        district: "بيت بوس",
        area: 110,
        rooms: 2,
        bathrooms: 2,
        floor: 2,
        features: ["مطبخ مجهز", "بناء حديث", "قريب من المولات"],
        images: ["/Check-/images/modern_kitchen_apartment.png"],
        status: "available",
        created_at: new Date().toISOString()
    },
    {
        id: 6,
        title: "جناح نوم فاخر في فيلا بالروضة",
        description: "غرفة نوم رئيسية واسعة مع حمام خاص وتصميمات داخلية فاخرة تضمن الراحة والسكينة.",
        type: "villa",
        price: 300000,
        city: "صنعاء",
        district: "الروضة",
        area: 250,
        rooms: 4,
        bathrooms: 3,
        floor: 1,
        features: ["هدوء", "تصميم فاخر", "حراسة"],
        images: ["/Check-/images/luxury_bedroom_villa_yemen.png"],
        status: "available",
        created_at: new Date().toISOString()
    }
];
